# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.2.21"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJSON = "1.9.0"
kotlinxCoroutines = "1.10.2"
skainet = "0.6.3"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinxDatetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinxSerialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJSON" }
kotlinxCoroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
skainet-lang-core = { module = "sk.ainet.core:skainet-lang-core", version.ref = "skainet" }
skainet-backend-cpu = { module = "sk.ainet.core:skainet-backend-cpu", version.ref = "skainet" }
skainet-lang-models = { module = "sk.ainet.core:skainet-lang-models", version.ref = "skainet" }
skainet-model-yolo = { module = "sk.ainet.core:skainet-model-yolo", version.ref = "skainet" }
skainet-io-image = { module = "sk.ainet.core:skainet-io-image", version.ref = "skainet" }


# Libraries can be bundled together for easier import
[bundles]
kotlinxEcosystem = ["kotlinxDatetime", "kotlinxSerialization", "kotlinxCoroutines"]
skainet = ["skainet-lang-core", "skainet-backend-cpu", "skainet-lang-models", "skainet-model-yolo", "skainet-io-image"]

[plugins]
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }